trigger:
  branches:
    include:
      - feature/*
      - hotfix/*
      - bug/*

  paths:
    include:
      - "*.tf"
      - "*.hcl"
      - "*.tfvars"
      - ".azuredevops/"
      - "infra/"
    exclude:
      - "infra/documentation/"
      - "infra/docs/"
      - "infra/*.md"

variables:
  - group: terraform-secrets
  - group: terraform-common

resources:
  repositories:
    - repository: templates
      type: git
      name: AzureTestFM/terraform-pipelines-azure
      ref: "refs/heads/main"

extends:
  template: terraform-validate.yaml@templates
