name: Terraform infrastruture deployment


on: 
  push:
    branches:
      - main
      - fmtestbranch

    pull_request:
    workflow_dispatch:

env:
  tf_resource_group_name: "rg-fmtest-sb-eus2"
  tf_storage_account_name: "safmtestsbeus2"
  tf_state_container: "blob-fmtest-tfstate"
  tf_state_key: "AzureTestFM.tfstate"

jobs:
  terraform-fmt-check:
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: ./terraform
    name: terraform
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.5.0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
           
    - name: Terraform Init
      id: init
      run: terraform init -backend-config="resource_group_name=$tf_resource_group_name" -backend-config="storage_account_name=$tf_storage_account_name" -backend-config="container_name=$tf_state_container" -backend-config="key=$tf_state_key"
     
        env:
          ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
        working-directory: ./terraform

        - name: Terraform Fmt
        id: fmt
        run: terraform fmt
        working-directory: ./terraform