name: Terraform infra deployment

on:
  workflow_dispatch:
    branches:
      - main
      - fmtestbranch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
       
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform init
        id: init
        run: |

          az login --service-principal \
            -u ${{ secrets.ARM_CLIENT_ID }} \
            -p ${{ secrets.ARM_CLIENT_SECRET }} \
            --tenant ${{ secrets.ARM_TENANT_ID }} 
                   
          terraform init

       
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve


