name: Terraform state deployment


on: 
  workflow_dispatch:
    branches:
      - main
      - fmtestbranch

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        
    steps:
  # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

  # Login and connect to the storage for the state file
    - name: 'Az  login'
            
          set -a 
             az login --service-principal \
            -u ${{ secrets.ARM_CLIENT_ID }} \
            -p ${{ secrets.ARM_CLIENT_SECRET }} \
            --tenant ${{ secrets.ARM_TENANT_ID }} \
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      
