name: Terraform infrastruture deployment


on: 
  push:
    branches:
      - main
      - fmtestbranch


jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
       
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Azure Authentication
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform init
        id: init
        run: |      
          terraform init

       
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve


